### ISSUE TITLE
Add support for configuration files

### ISSUE THREAD

**Issue by junkert** [opendns/lemming#11]
If we add support for configuration files we can easily run applications once checked out from github on different infrastructures and test environments. This file would hold things such as:

1, username
2. password
3. default database host
4. default database port
5. default database
6. alternate database hosts (or a list of read/write hosts)

Example / HowTo would be useful.

**Comment by simar7** [comment]
Good idea. I can take a look into this.

**Comment by simar7** [comment]
I've added support for this: https://github.com/opendns/lemming/commit/22c9144d6a8dbcfd56aae8aabd6186081d66bcb3  we can always expand for other args
